"""Command-line entry point. Model output goes to stdout; errors go to stderr."""
import argparse
import json
from pathlib import Path
import sys

from .client import available, count_tokens, respond
from .worker import JOBS, paperclip, run_job


def main():
    parser = argparse.ArgumentParser(description='Use Apple’s on-device Foundation Model through fm')
    commands = parser.add_subparsers(dest='command', required=True)
    commands.add_parser('available', help='Check local model availability')
    response = commands.add_parser('respond', help='Generate text; read stdin if prompt is omitted')
    response.add_argument('prompt', nargs='?')
    response.add_argument('--instructions')
    response.add_argument('--image', type=Path)
    response.add_argument('--schema', type=Path, help='Schema file generated by fm schema')
    response.add_argument('--timeout', type=float, default=90)
    tokens = commands.add_parser('count-tokens', help='Count text tokens; read stdin if omitted')
    tokens.add_argument('prompt', nargs='?')
    tokens.add_argument('--instructions')
    job = commands.add_parser('job', help='Run a validated advisory job on JSON stdin')
    job.add_argument('--job', choices=JOBS)
    job.add_argument('--paperclip', action='store_true')
    job.add_argument('--publish', action='store_true', help='Check out task and publish advisory document')
    args = parser.parse_args()
    if args.command == 'job' and args.publish and not args.paperclip:
        parser.error('--publish requires --paperclip')
    if args.command == 'job' and args.paperclip and not args.job:
        parser.error('--paperclip requires --job')
    if args.command == 'respond' and args.timeout <= 0:
        parser.error('--timeout must be positive')
    try:
        if args.command == 'available':
            print(available())
        elif args.command in ('respond', 'count-tokens'):
            prompt = args.prompt if args.prompt is not None else sys.stdin.read()
            if args.command == 'count-tokens':
                print(count_tokens(prompt, instructions=args.instructions))
            else:
                schema = args.schema.read_text() if args.schema else None
                print(respond(prompt, instructions=args.instructions, image=args.image, schema=schema, timeout=args.timeout))
        elif args.paperclip:
            print(json.dumps(paperclip(args.job, args.publish), ensure_ascii=False))
        else:
            request = json.load(sys.stdin)
            if args.job:
                if not isinstance(request, dict):
                    raise ValueError('Request must be a JSON object')
                request['job'] = args.job
            print(json.dumps(run_job(request), ensure_ascii=False))
    except Exception as exc:
        print(json.dumps({'status': 'error', 'error': str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 1
    return 0
